//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employees
    {
        public tbl_Employees()
        {
          this.tbl_PyInOut = new HashSet<tbl_PyInOut>();
        }
    
        public int ID { get; set; }
        public string EmployeeId { get; set; }
        public string Employee_Name { get; set; }
        public string Guarantor { get; set; }
        public string Mobile { get; set; }
        public string EmplyeeImg { get; set; }
        public DateTime HireDate { get; set; }
    
        public virtual ICollection<tbl_PyInOut> tbl_PyInOut { get; set; }
    }
}
